### ISSUE TITLE
wall shear stress for two phase flows

### ISSUE THREAD

**Issue by sasankheirandish** [fppimenta/rheoTool#9] opened 2019-03-03 12:36 UTC
Dear Francisco Pimenta
I monitored wall shear stress for two phase flows. but I got zero values for WSS. I added the calcWSS.c function to fvsolution. For one -phase flow the results were correct.  however,  this was not true for two phase flows which are should be run by rheointerFoam solver. 
How can i solve my problem?
Best regards

**Comment by fppimenta** [comment] 2019-03-03 13:08
Are you using rheoTool for of60?

**Comment by sasankheirandish** [comment] 2019-03-03 13:17
yeah. openFoam 6

**Comment by fppimenta** [comment] 2019-03-03 13:33
So the problem is in a bug for this version, in rheoInterFoam.C. This has already been corrected in the new version of rheoTool (v4), which will be released soon. You have 2 options: use the version for of40 (free of this bug) or correct the bug in of60, which is quite simple. The bug is this one: in file rheoInterFoam.C, add this line

      postProc.update();

above the line

      runTime.write();

Then recompile and it should be fine. Do not forget to set isTwoPhaseFlow as true in fvSolution.

**Comment by sasankheirandish** [comment] 2019-03-03 18:26
thank you very much

**Closed** 2019-03-05 14:03 UTC

**Comment by pratyush507** [comment] 2023-01-29 05:33
@sasankheirandish can you please share the code or steps how to calculate the wall shear stress as i want to get the walls shear stress distribution and i am using rheoFoam solver. Please help.
